gcp:
  subscription: pull-subscription

spring:
  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 5
      project-id: neural-land-324105
