gcp:
  subscription: pull-subscription
  subscriber:
    pull:
      enabled: ${PULL_SUBSCRIBER_ENABLED:false}
    push:
      enabled: ${PUSH_SUBSCRIBER_ENABLED:true}

spring:
  cloud:
    gcp:
      pubsub:
        subscriber:
          flow-control:
            max-outstanding-element-count: 5
      project-id: neural-land-324105
