name: Docker build and push to Artifact Registry

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: neural-land-324105
  GAR_LOCATION: us-central1
  REPOSITORY: us-central-docker
  IMAGE: flow-control-demo

jobs:
  login-build-push:
    name: Docker login, build, and push
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: 'Docker build'
        run: |-
          ./mvnw spring-boot:build-image -Dspring-boot.build-image.imageName="$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0.6.0'
        with:
          workload_identity_provider: 'projects/486774505123/locations/global/workloadIdentityPools/github-identity-pool/providers/github-provider'
          service_account: 'github-action@neural-land-324105.iam.gserviceaccount.com'
          token_format: 'access_token'

      - uses: 'docker/login-action@v2'
        name: 'Docker login'
        with:
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: 'Docker push'
        run: |-
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: 'pusub-push-endpoint'
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ env.GITHUB_SHA }}"

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
